use ESG

only_tables (TABLE_CATALOG, TABLE_NAME, TABLE_TYPE, TABLE_SCHEMA)
 AS (SELECT TABLE_CATALOG, TABLE_NAME, TABLE_TYPE, TABLE_SCHEMA 
 FROM all_tables
 WHERE TABLE_TYPE != 'VIEW' 
 AND 
 TABLE_SCHEMA != 'DATAMART' ),

grouped_table (TABLE_SCHEMA,TABLE_NAME, TABLE_TYPE,  "RANK")
as 
(SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, RANK() 
OVER(PARTITION BY TABLE_SCHEMA ORDER BY TABLE_NAME ) AS ROWNUMBER 
FROM only_tables)

SELECT TABLE_NAME 
FROM grouped_table
WHERE TABLE_SCHEMA = 'CTG'
